In [1]:
import numpy as np


In [2]:
a = np.array([[1, 2, 4], [5, 8, 7]])

print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1 2 4]
 [5 8 7]]


In [3]:
b = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", b)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
c = np.full((3, 3), 6)
print ("\nAn array initialized with all 6s.\n", c)


An array initialized with all 6s.
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [5]:
d = np.random.random((2, 2))
print ("\nA random array:\n", d)


A random array:
 [[0.68987426 0.21819891]
 [0.53534633 0.00830126]]


In [6]:
e = np.arange(0, 30, 5)
print ("\nA sequential array with steps of 5:\n", e)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [7]:
arr = np.array([[1, 2, 3, 4],

[5, 2, 4, 2],

[1, 2, 0, 1]])

newarr = arr.reshape(4, 3)

print ("\nOriginal array:\n", arr)

print ("Reshaped array[4,3]:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [9]:


print("\nNo. of dimensions: ", arr.ndim)


No. of dimensions:  2


In [10]:
print("\nShape of array: ", arr.shape)


Shape of array:  (3, 4)


In [11]:
print("\nSize of array: ", arr.size)


Size of array:  12


In [12]:
print("\nArray stores elements of type: ",
arr.dtype)


Array stores elements of type:  int32


In [13]:
flarr = arr.flatten()

print ("\nOriginal array:\n", arr)

print ("Fattened array:\n", flarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Fattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [14]:
newtype=arr.astype('f')
print("\nConverted array elements:\n",newtype)
print("Converted array type:",newtype.dtype)


Converted array elements:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
Converted array type: float32


In [17]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
print arr
print arr[[4, 3, 0, 6]]
print arr[[-3, -5, -7]]

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (1724159176.py, line 4)

In [19]:
arr = np.array([[1, 2, 3, 4],
[5, 2, 4, 2],
[3, 5, 8, 9],
[5, 9, 2, 0],
[1, 2, 0, 1]])
print("every alternate row\n",arr[0:4:2])
print("first 2 rows and 3 columns\n",arr[:2,:3])
print("except first 2 rows and 2 columns\n",arr[2:,2:])
print("extracting 2nd row, 3rd value\n",arr[2,3])
print("first 2 rows\n", arr[:2])
print("except first 3 rows\n",arr[3:])
print("first 3 columns\n",arr[:,:3])

every alternate row
 [[1 2 3 4]
 [3 5 8 9]]
first 2 rows and 3 columns
 [[1 2 3]
 [5 2 4]]
except first 2 rows and 2 columns
 [[8 9]
 [2 0]
 [0 1]]
extracting 2nd row, 3rd value
 9
first 2 rows
 [[1 2 3 4]
 [5 2 4 2]]
except first 3 rows
 [[5 9 2 0]
 [1 2 0 1]]
first 3 columns
 [[1 2 3]
 [5 2 4]
 [3 5 8]
 [5 9 2]
 [1 2 0]]


In [20]:
print("Original array:\n", arr)
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
"(3, 0):\n", temp)

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [3 5 8 9]
 [5 9 2 0]
 [1 2 0 1]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4 4 5 5]


In [21]:
cond = arr > 2
temp = arr[cond]
print ("\nElements greater than 2:\n",
temp)


Elements greater than 2:
 [3 4 5 4 3 5 8 9 5 9]


In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print("\nOriginal arrays:\n",arr1,arr2)
print("\nJoined array:\n",arr)


Original arrays:
 [1 2 3] [4 5 6]

Joined array:
 [1 2 3 4 5 6]


In [23]:
arr = np.hstack((arr1, arr2))
print("\horizontal joining:\n",arr)

\horizontal joining:
 [1 2 3 4 5 6]


In [24]:
print("\nOriginal arrays:\n",arr1,arr2)

arr = np.vstack((arr1, arr2))
print("\nVertical joining:\n",arr)


Original arrays:
 [1 2 3] [4 5 6]

Vertical joining:
 [[1 2 3]
 [4 5 6]]


In [25]:
arr = np.dstack((arr1, arr2))
print("\nDepth joining:\n",arr)


Depth joining:
 [[[1 4]
  [2 5]
  [3 6]]]


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print("\nOriginal Array:\n",arr)
print("\nSplitted array:\n",newarr)


Original Array:
 [1 2 3 4 5 6]

Splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]


In [27]:
print("\nSplit array in another form:\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])


Split array in another form:

[1 2]
[3 4]
[5 6]
